# Generated by Django 3.2.6 on 2021-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(verbose_name='website')),
                ('cv', models.FileField(upload_to='apply', verbose_name='cv')),
                ('cover_letter', models.TextField(verbose_name='cover letter')),
            ],
            options={
                'verbose_name': 'Apply',
                'verbose_name_plural': 'Applies',
            },
        ),
    ]
