# Generated by Django 3.2.6 on 2021-08-04 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='job'),
        ),
    ]
